# Recurrent Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from pandas.plotting import lag_plot
from pandas import datetime
from statsmodels.tsa.arima_model import ARIMA
from sklearn.metrics import mean_squared_error

### Importing the training set

In [ ]:
dataset = pd.read_csv('/content/PRSA_data_2010.1.1-2014.12.31.csv')


In [ ]:
dataset.head()

No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

In [ ]:
dataset.shape

(43824, 13)

In [ ]:
dataset = dataset.dropna(how='any',axis=0) 

In [ ]:
dataset.shape

(41757, 13)

In [ ]:
dataset.head()

No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd   Iws  Is  Ir
24  25  2010      1    2     0  129.0   -16  -4.0  1020.0   SE  1.79   0   0
25  26  2010      1    2     1  148.0   -15  -4.0  1020.0   SE  2.68   0   0
26  27  2010      1    2     2  159.0   -11  -5.0  1021.0   SE  3.57   0   0
27  28  2010      1    2     3  181.0    -7  -5.0  1022.0   SE  5.36   1   0
28  29  2010      1    2     4  138.0    -7  -5.0  1022.0   SE  6.25   2   0

In [ ]:
train_data, test_data = dataset[0:int(len(dataset)*0.9)], dataset[int(len(dataset)*0.9):]
training_data = train_data['pm2.5'].values

In [ ]:

test_data = test_data['pm2.5'].values
history = [x for x in training_data]


In [ ]:
model_predictions = []
N_test_observations = len(test_data)
for time_point in range(N_test_observations):
    model = ARIMA(history, order=(4,1,0))
    model_fit = model.fit(disp=0)
    output = model_fit.forecast()
    yhat = output[0]
    model_predictions.append(yhat)
    true_test_value = test_data[time_point]
    history.append(true_test_value)


/usr/local/lib/python3.6/dist-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [ ]:
MSE_error = mean_squared_error(test_data, model_predictions)
print('Testing Mean Squared Error is {}'.format(MSE_error))

Testing Mean Squared Error is 347.65042462949356


In [ ]:
model_predictions

[array([155.9656694]),
 array([164.95552242]),
 array([140.49914331]),
 array([136.92869883]),
 array([130.50442957]),
 array([112.77467239]),
 array([60.88011219]),
 array([21.71812398]),
 array([17.35068926]),
 array([16.14820857]),
 array([9.57409619]),
 array([13.90464954]),
 array([10.51856179]),
 array([7.60328239]),
 array([10.52557655]),
 array([16.96406532]),
 array([54.39405073]),
 array([42.22420814]),
 array([41.37348759]),
 array([57.25164225]),
 array([51.91430243]),
 array([90.60583226]),
 array([26.60884986]),
 array([18.49698746]),
 array([22.65354771]),
 array([15.50889947]),
 array([17.58514016]),
 array([16.9680548]),
 array([15.84923353]),
 array([10.17888466]),
 array([11.31027804]),
 array([14.57325582]),
 array([7.97824555]),
 array([8.09923214]),
 array([10.43116481]),
 array([14.61785956]),
 array([13.74286812]),
 array([23.34182219]),
 array([33.22692558]),
 array([36.01429065]),
 array([27.38541243]),
 array([31.6644877]),
 array([35.6093859]),
 array([33.61